In [ ]:
# 1) Split this string:

s= "Hi there San!"

print(s.split())

['Hi', 'there', 'San!']


In [ ]:
# 2) Use .format() to print the following string.

planet = "Earth"
diameter= 12742

print("The diameter of {planet} is {diameter} kilometers".format(planet = "Earth",diameter= 12742))

The diameter of Earth is 12742 kilometers


In [ ]:
# 3)

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

print(d['k1'][3]['tricky'][3]['target'][3])

hello


In [ ]:
# Numpy

# 4.1) Create an array of 10 zeros:

import numpy as np

array=np.zeros(10)
print(array)



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# 4.2) Create an array of 10 fives:

import numpy as np

array=np.ones(10)*5
print(array)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
# 5) Array of all even intergers from 20 to 35:

import numpy as np

array=np.arange(20,35,2)
print(array)


[20 22 24 26 28 30 32 34]


In [ ]:
#6) Create a 3x3 matrix values ranging from 0 to 8:

import numpy as np

b = np.arange(0,9).reshape(3,3)
print(b)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# 7) Concatinate a and b:

a = np.array([1,2,3])
b = np.array([4,5,6])

c= np.concatenate((a,b),axis = None)

print(c)

[1 2 3 4 5 6]


In [ ]:
# Pandas:
#8) Create a dataframe using 3 rows and 3 columns:

import pandas as pd

data=[1,2],[4,5],[7,8]
df = pd.DataFrame(data, columns=['a', 'b'])
df


a  b
0  1  2
1  4  5
2  7  8

In [ ]:
#9) Generate the series of dates from 1st jan ,2023 to 10 feb, 2023 :

import pandas as pd

df = pd.date_range(start='1/1/2023', end='10/02/2023')
df


DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=275, freq='D')

In [ ]:
# 10) Create 2D list to DataFrame:

import pandas as pd
list = [[1,'aaa',22],[2,'bbb',25],[3,'ccc',24]]

df = pd.DataFrame(list,columns =("no","string","int"))
df



no string  int
0   1    aaa   22
1   2    bbb   25
2   3    ccc   24